// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PrelazakUPrivilegovanogKorisnika_Uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PrelazakUPrivilegovanogKorisnika_Uspesno', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/home")
    await driver.manage().window().setRect(1536, 824)
    await driver.findElement(By.linkText("Moj profil")).click()
    await driver.findElement(By.linkText("Privilegije")).click()
    assert(await driver.findElement(By.css(".no-priv-status")).getText() == "TRENUTNO NEMATE PRIVILEGIJE")
    {
      const elements = await driver.findElements(By.css(".no-priv-button"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".no-priv-button")).click()
    await driver.findElement(By.css(".btn-outline-success")).click()
    assert(await driver.findElement(By.css(".yes-priv-status")).getText() == "CESTITAMO, POSTALI STE PRIVILEGOVANI KORISNIK")
  })
})
