// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PrelazakUPrivilegovanogKorisnika_VecPrivilegovan', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PrelazakUPrivilegovanogKorisnika_VecPrivilegovan', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.linkText("Moj profil")).click()
    await driver.findElement(By.linkText("Privilegije")).click()
    assert(await driver.findElement(By.css(".yes-priv-status")).getText() == "VEC STE PRIVILEGOVANI KORISNIK")
  })
})
