// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PrelazakUPrivilegovanogKorisnika_NemaDovoljnoNovca', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PrelazakUPrivilegovanogKorisnika_NemaDovoljnoNovca', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/")
    await driver.manage().window().setRect(1536, 824)
    await driver.findElement(By.linkText("Moj profil")).click()
    await driver.findElement(By.linkText("Privilegije")).click()
    assert(await driver.findElement(By.css(".no-priv-status")).getText() == "TRENUTNO NEMATE PRIVILEGIJE")
    {
      const elements = await driver.findElements(By.css(".no-priv-button"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".no-priv-button")).click()
    {
      const element = await driver.findElement(By.css(".no-priv-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    assert(await driver.findElement(By.css("#error p")).getText() == "Na vasem racunu je manje od 30 €. Ne mozete ostvariti status privilegovanog korisnika.")
    await driver.findElement(By.css("#error .btn")).click()
  })
})
