// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PregledTransakcija_greskaFilter', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PregledTransakcija_greskaFilter', async function() {
    await driver.get("http://localhost/bela_berza/public/WalletController")
    await driver.manage().window().setRect(1920, 1040)
    await driver.findElement(By.name("tipAkcije")).click()
    {
      const dropdown = await driver.findElement(By.name("tipAkcije"))
      await dropdown.findElement(By.xpath("//option[. = 'Kupovine']")).click()
    }
    await driver.findElement(By.name("tipAkcije")).click()
    await driver.findElement(By.css("form:nth-child(8) .btn")).click()
    assert(await driver.findElement(By.xpath("(//div[@id=\'walletTable\'])[2]")).getText() == "Ne postoje akcije sa zadatim filtrom!")
  })
})
