// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PregledTransakcijaKupovine_uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PregledTransakcijaKupovine_uspesno', async function() {
    await driver.get("http://localhost/bela_berza/public/WalletController")
    await driver.manage().window().setRect(1936, 1056)
    await driver.findElement(By.name("tipAkcije")).click()
    {
      const dropdown = await driver.findElement(By.name("tipAkcije"))
      await dropdown.findElement(By.xpath("//option[. = 'Kupovine']")).click()
    }
    await driver.findElement(By.name("tipAkcije")).click()
    await driver.findElement(By.css("form:nth-child(8) .btn")).click()
    assert(await driver.findElement(By.css("tr:nth-child(1) > .wallet-out:nth-child(2)")).getText() == "Kupovina")
    assert(await driver.findElement(By.css("tr:nth-child(2) > .wallet-out:nth-child(2)")).getText() == "Kupovina")
  })
})
