// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Kupovina_neuspesna', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Kupovina_neuspesna', async function() {
    await driver.get("http://localhost/bela_berza/public/Home")
    await driver.findElement(By.id("btnApple")).click()
    {
      const element = await driver.findElement(By.id("btnApple"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".fa-plus > path")).click()
    await driver.findElement(By.css(".btn-outline-success")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "×\\\\nNeuspešna kupovina akcije/a! Nažalost, nije moguće kupiti zahtevani broj akcija. Proverite njihovu trenutnu dostupnost i pokušajte ponovo.")
  })
})
