// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_IsplataNovca_Greska_NepostojeciRacun', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_IsplataNovca_Greska_NepostojeciRacun', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/home")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.css("li:nth-child(3) span")).click()
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.findElement(By.name("amountInputFieldWithdraw")).click()
    await driver.findElement(By.name("amountInputFieldWithdraw")).sendKeys("1000")
    await driver.findElement(By.id("bankAccountNumberInput")).click()
    await driver.findElement(By.id("bankAccountNumberInput")).sendKeys("123-1234567812345-44")
    await driver.findElement(By.css(".modal-footer:nth-child(5) > .btn-outline-success")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "×\\\\nNeuspešna transakcija! Broj računa ne postoji u banci, molimo Vas proverite broj računa!")
  })
})
