// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registracija_greskaLozinka', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registracija_greskaLozinka', async function() {
    await driver.get("http://localhost/bela_berza/public/")
    await driver.findElement(By.css("li:nth-child(2) span")).click()
    await driver.findElement(By.css(".login-html > .tab:nth-child(4)")).click()
    await driver.findElement(By.name("nameReg")).click()
    await driver.findElement(By.name("nameReg")).sendKeys("Kosta")
    await driver.findElement(By.name("surnameReg")).sendKeys("Matijevic")
    await driver.findElement(By.id("usernameInputField")).sendKeys("kostamat")
    await driver.findElement(By.name("emailReg")).sendKeys("leko.matijevic@gmail.com")
    await driver.findElement(By.name("passwordReg")).sendKeys("kosta123")
    await driver.findElement(By.css(".btn-outline-danger")).click()
    assert(await driver.findElement(By.css(".alert")).getText() == "×\\\\nRegistracija odbijena - lozinka mora sadrzati bar jedno veliko slovo!")
  })
})
