// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PregledFAQGost_uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PregledFAQGost_uspesno', async function() {
    await driver.get("http://localhost/bela_berza/public/home")
    await driver.manage().window().setRect(1936, 1056)
    await driver.findElement(By.linkText("FAQ")).click()
    assert(await driver.findElement(By.css(".row:nth-child(5) h4")).getText() == "1. Ko su korisnici ovog sistema?")
  })
})
