// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PotvrdaRegistracijeKorisnika_OdbijenaRegistracija', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PotvrdaRegistracijeKorisnika_OdbijenaRegistracija', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/home")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.css("li:nth-child(2) > .menu-item > span")).click()
    {
      const elements = await driver.findElements(By.css("tr:nth-child(1) .fa-times-circle > path"))
      assert(elements.length)
    }
    await driver.findElement(By.css("tr:nth-child(1) .fa-times-circle")).click()
    assert(await driver.findElement(By.css("#rejectModal #exampleModalLongTitle")).getText() == "Odbijanje registracije")
    await driver.findElement(By.id("rejectBtn")).click()
    assert(await driver.findElement(By.css("h1:nth-child(2)")).getText() == "BELA BERZA")
  })
})
