// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PotvrdaRegistracijeKorisnika_Uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PotvrdaRegistracijeKorisnika_Uspesno', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/Home")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.linkText("Pregled registracija")).click()
    {
      const elements = await driver.findElements(By.css("tr:nth-child(1) .fa-check-circle > path"))
      assert(elements.length)
    }
    await driver.findElement(By.css("tr:nth-child(1) .fa-check-circle > path")).click()
    assert(await driver.findElement(By.id("exampleModalLongTitle")).getText() == "Potvrda registracije")
    await driver.findElement(By.id("confirmBtn")).click()
    await driver.findElement(By.css("h1:nth-child(2)")).click()
    await driver.findElement(By.css("h1:nth-child(2)")).click()
    assert(await driver.findElement(By.css("h1:nth-child(2)")).getText() == "BELA BERZA")
  })
})
