// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PregledOdabranihAkcija_Uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PregledOdabranihAkcija_Uspesno', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/Home")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.css(".col-6:nth-child(1) img")).click()
    {
      const elements = await driver.findElements(By.css(".canvasjs-chart-panel:nth-child(7) .canvasjs-chart-canvas:nth-child(2)"))
      assert(elements.length)
    }
  })
})
