// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SSU_PregledCelokupneIstorijeTransakcija_Uspesno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SSU_PregledCelokupneIstorijeTransakcija_Uspesno', async function() {
    await driver.get("http://localhost/Bela_Berza/Implementacija/public/")
    await driver.manage().window().setRect(1536, 824)
    await driver.findElement(By.css("li:nth-child(3) span")).click()
    {
      const elements = await driver.findElements(By.css("tr:nth-child(1) > .wallet-out:nth-child(3)"))
      assert(elements.length)
    }
  })
})
