// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PregladUplataIsplata_greskaPrazno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PregladUplataIsplata_greskaPrazno', async function() {
    await driver.get("http://localhost/bela_berza/public/WalletController")
    await driver.manage().window().setRect(1920, 1040)
    await driver.findElement(By.css("form:nth-child(5) .btn")).click()
    assert(await driver.findElement(By.id("walletTable")).getText() == "Nemate ni uplate ni isplate na vasem nalogu!")
  })
})
