// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Prodaja_uspesna', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Prodaja_uspesna', async function() {
    await driver.get("http://localhost/bela_berza/public/collection/bela_berza/public/collection")
    await driver.findElement(By.id("btnMicrosoft")).click()
    await driver.findElement(By.id("quantityplus")).click()
    await driver.findElement(By.id("quantityplus")).click()
    await driver.findElement(By.css(".btn-outline-success")).click()
    assert(await driver.findElement(By.css(".alert > strong")).getText() == "Prodaja je uspešno okončana i sredstva na vašem računu su ažurirana!")
  })
})
